version: "3.3"
services:
  postgres:
    image: postgres:11.8-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=kafka
      - POSTGRES_USER=kafka
      - POSTGRES_PASSWORD=kafka
      - MAX_CONNECTIONS=300